title: The RECeSS project
email: recess-project@proton.me
url: RECeSS-EU-Project.github.io
webmaster: Clémence Réda
description: "The RECeSS project aims at bridging the gap between drug research and collaborative filtering algorithms, in order to implement better in silico drug recommender systems and help define more sustainable and transparent drug development for rare diseases. The RECeSS (Robust Explainable Controllable Standard for drug Screening) project is funded by a Marie Skłodowska-Curie Postdoctoral Fellowship 2022 (Horizon Europe)."
twitter_username: recess_eu_proj
github_username: RECeSS-EU-Project
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

analytics:
#  provider: "google-gtag"
  google:
    tracking_id: "G-YVEBR1XRP0"
    anonymize_ip: false

after_footer_scripts:
  - /assets/js/cookie-consent.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Robust Explainable Controllable Standard for drug Screening (RECeSS)"
  avatar : "/assets/images/icon.jpeg"
  bio    : "Follow the progress of the RECeSS research project, and discuss it with us on social media! ☟"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/recess_eu_proj"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RECeSS-EU-Project"

footer:

atom_feed: 
    - hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
